spring:
  data:
    mongodb:
      database: newscms
      host: localhost
      port: 27017
# PostgreSQL
#  datasource:
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
#    password: newscms@codespring
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    show-sql: true   #log SQL instructions to console
#    generate-ddl: true   #Create tables in DB when application starts